"""devgraph authorization vocabulary and models."""

from devgraph.auth.context import AuthorityContext
from devgraph.auth.credentials import CredentialEnvelope
from devgraph.auth.enforcement import (
    AuditLog,
    AuditRecord,
    AuthorizedWorkGraph,
    WriteSession,
    require_scope,
)
from devgraph.auth.errors import AuthError, ForbiddenError, UnauthenticatedError
from devgraph.auth.local_read import (
    AUTH_MODE_LOCAL_READ,
    LOCAL_READ_CREDENTIAL_PREFIX_V1,
    LOCAL_READ_MAX_LIFETIME_SECONDS,
    LOCAL_READ_REGISTRY_RELATIVE_PATH,
    LOCAL_READ_REGISTRY_SCHEMA_V1,
    LocalReadCredentialConfigurationError,
    LocalReadCredentialVerifier,
)
from devgraph.auth.scopes import (
    ALL_CATEGORIES,
    ALL_SCOPES,
    CATEGORY_ADMIN,
    CATEGORY_EXPORT_INTERNAL,
    CATEGORY_EXPORT_REDACTED,
    CATEGORY_READ,
    CATEGORY_SKILL_USE,
    CATEGORY_TOOL_USE,
    CATEGORY_WRITE,
    REQUIRED_SCOPE_BY_CATEGORY,
    SCOPE_ADMIN,
    SCOPE_EXPORT_INTERNAL,
    SCOPE_EXPORT_REDACTED,
    SCOPE_READ,
    SCOPE_SKILL_USE,
    SCOPE_TOOL_USE,
    SCOPE_WRITE,
)
from devgraph.auth.secs_issue_create import (
    DEVGRAPH_ISSUE_CREATE_OPERATION_V1,
    SecSIssueCreateAdapter,
    SecSIssueCreateDenied,
    SecSIssueCreatePolicyBinding,
    SecSIssueCreatePolicyRegistry,
    SecSIssueCreateResult,
    SecSIssueCreateVerifier,
    SecSIssueCreateVerifierConfig,
    SecSVerifierKey,
    SecSVerifierKeyRegistry,
)
from devgraph.auth.verifier import (
    AUTH_MODE_ENV_VAR,
    AUTH_MODE_LOCAL_DEV,
    CredentialVerifier,
    LocalDevVerifier,
)

__all__ = [
    "ALL_CATEGORIES",
    "ALL_SCOPES",
    "AUTH_MODE_ENV_VAR",
    "AUTH_MODE_LOCAL_DEV",
    "AUTH_MODE_LOCAL_READ",
    "AuditLog",
    "AuditRecord",
    "AuthError",
    "AuthorityContext",
    "AuthorizedWorkGraph",
    "CATEGORY_ADMIN",
    "CATEGORY_EXPORT_INTERNAL",
    "CATEGORY_EXPORT_REDACTED",
    "CATEGORY_READ",
    "CATEGORY_SKILL_USE",
    "CATEGORY_TOOL_USE",
    "CATEGORY_WRITE",
    "CredentialEnvelope",
    "CredentialVerifier",
    "DEVGRAPH_ISSUE_CREATE_OPERATION_V1",
    "ForbiddenError",
    "LocalDevVerifier",
    "LOCAL_READ_CREDENTIAL_PREFIX_V1",
    "LOCAL_READ_MAX_LIFETIME_SECONDS",
    "LOCAL_READ_REGISTRY_RELATIVE_PATH",
    "LOCAL_READ_REGISTRY_SCHEMA_V1",
    "LocalReadCredentialConfigurationError",
    "LocalReadCredentialVerifier",
    "REQUIRED_SCOPE_BY_CATEGORY",
    "SCOPE_ADMIN",
    "SCOPE_EXPORT_INTERNAL",
    "SCOPE_EXPORT_REDACTED",
    "SCOPE_READ",
    "SCOPE_SKILL_USE",
    "SCOPE_TOOL_USE",
    "SCOPE_WRITE",
    "SecSIssueCreateAdapter",
    "SecSIssueCreateDenied",
    "SecSIssueCreatePolicyBinding",
    "SecSIssueCreatePolicyRegistry",
    "SecSIssueCreateResult",
    "SecSIssueCreateVerifier",
    "SecSIssueCreateVerifierConfig",
    "SecSVerifierKey",
    "SecSVerifierKeyRegistry",
    "UnauthenticatedError",
    "WriteSession",
    "require_scope",
]
